# Generated by Django 5.2.10 on 2026-08-13 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roomvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendships',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roomvisit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='roomvisit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='roomvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_5feac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendships',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friendship_direction'),
        ),
        migrations.AddConstraint(
            model_name='friendships',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='friendship_not_self'),
        ),
        migrations.AddConstraint(
            model_name='roomvisit',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_room_visit'),
        ),
    ]
