/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReinitialiserTokenRouteImport } from './routes/reinitialiser.$token'
import { Route as RejoindreTokenRouteImport } from './routes/rejoindre.$token'
import { Route as VerifierEmailTokenRouteImport } from './routes/verifier-email.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserTokenRoute = ReinitialiserTokenRouteImport.update({
  id: '/reinitialiser/$token',
  path: '/reinitialiser/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreTokenRoute = RejoindreTokenRouteImport.update({
  id: '/rejoindre/$token',
  path: '/rejoindre/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierEmailTokenRoute = VerifierEmailTokenRouteImport.update({
  id: '/verifier-email/$token',
  path: '/verifier-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/register': typeof RegisterRoute
  '/reinitialiser/$token': typeof ReinitialiserTokenRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/register': typeof RegisterRoute
  '/reinitialiser/$token': typeof ReinitialiserTokenRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/register': typeof RegisterRoute
  '/reinitialiser/$token': typeof ReinitialiserTokenRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/verifier-email/$token': typeof VerifierEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/register'
    | '/reinitialiser/$token'
    | '/rejoindre/$token'
    | '/verifier-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/register'
    | '/reinitialiser/$token'
    | '/rejoindre/$token'
    | '/verifier-email/$token'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/register'
    | '/reinitialiser/$token'
    | '/rejoindre/$token'
    | '/verifier-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  RegisterRoute: typeof RegisterRoute
  ReinitialiserTokenRoute: typeof ReinitialiserTokenRoute
  RejoindreTokenRoute: typeof RejoindreTokenRoute
  VerifierEmailTokenRoute: typeof VerifierEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser/$token': {
      id: '/reinitialiser/$token'
      path: '/reinitialiser/$token'
      fullPath: '/reinitialiser/$token'
      preLoaderRoute: typeof ReinitialiserTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre/$token': {
      id: '/rejoindre/$token'
      path: '/rejoindre/$token'
      fullPath: '/rejoindre/$token'
      preLoaderRoute: typeof RejoindreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-email/$token': {
      id: '/verifier-email/$token'
      path: '/verifier-email/$token'
      fullPath: '/verifier-email/$token'
      preLoaderRoute: typeof VerifierEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  RegisterRoute: RegisterRoute,
  ReinitialiserTokenRoute: ReinitialiserTokenRoute,
  RejoindreTokenRoute: RejoindreTokenRoute,
  VerifierEmailTokenRoute: VerifierEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
